AWSTemplateFormatVersion: 2010-09-09
Description: >
 Template launched by Service Catalog to deploy the networking layer in lab 6
Parameters:
  VPCCIDR:
    Description: CIDR Block for VPC
    Type: String
    Default: 10.96.10.0/16
    AllowedValues: [10.96.10.0/16]
  PUBSUBNET1:
    Description: Public Subnet A
    Type: String
    Default: 10.96.10.0/24
    AllowedValues: [10.96.10.0/24]
  PUBSUBNET2:
    Description: Public Subnet B
    Type: String
    Default: 10.96.15.0/24
    AllowedValues: [10.96.15.0/24]
  QwiklabLocale:
    Default: en
    Description: The locale of the student will be passed in to this parameter via the Qwiklab platform (via the student's browser)
    Type: String
Resources:
# Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: VPC
          Value: DevOps
        - Key: Name
          Value: CF Lab Env
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn:
      - VPC
    Properties:
      Tags:
        - Key: Name
          Value: DevOps VPC IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn:
      - VPC
      - InternetGateway
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PUBSUBNET1
      MapPublicIpOnLaunch : true
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public Subnet - A
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PUBSUBNET2
      MapPublicIpOnLaunch : true
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public Subnet - B
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public Routing Table
  PublicRouteIGW:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicRouteIGW
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable
  PublicRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicRouteIGW
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable
Outputs:
  VPC:
    Value: !Ref VPC
    Description: 'Exporting VPC Resource ID'
    Export:
      Name: 'VPC'
  PubSub1:
    Value: !Ref PublicSubnet1
    Description: 'Exporting PublicSubnet1 Resource ID'
    Export:
      Name: 'PUBSUB1'
  PubSub2:
    Value: !Ref PublicSubnet2
    Description: 'Exporting PublicSubnet2 Resource ID'
    Export:
      Name: 'PUBSUB2'